### PR TITLE
[DC-698] Update workflow_dispatch from v1 to v3

### PR DESCRIPTION
**Pull request by s-rubenstein**

### CODE REVIEW

**Review by pshapiro4broad — APPROVED** [review]
This looks OK. What do you think about updating the other GitHub actions while you're doing this? I see:

- broadinstitute/action-slack@v3.8.0, current is v3.15.0
- actions/upload-artifact@v1, current is v3
- google-github-actions/setup-gcloud@v0, current is v1
- databiosphere/github-actions/actions/bumper@bumper-0.0.6, current is 1.0.1 (I think)

**Comment by s-rubenstein** [comment]
@pshapiro4broad Can do! I'll look into it!

**Comment by s-rubenstein** [comment]
Looks like there's a bunch of upgrades, I'll just do a comprehensive upgrade!

**Comment by pshapiro4broad** [comment]
> I looked into the last tagged bumper version, and I think it is version 0.2.0: [DataBiosphere/github-actions/tags](https://github.com/DataBiosphere/github-actions/tags)

I wasn't sure if the `@xxx` refers to a tag or a release. The latest tag is `0.2.0` but the latest release is `0.1.0`. https://github.com/DataBiosphere/github-actions/releases. It probably uses tags?

**Comment by s-rubenstein** [comment]
It didn't shout at me for using 0.2.0 so I suspect tags!

**Review by nmalfroy — APPROVED** [review]
This looks good but I think you should have a Jira ticket associated for audit

**Pull request merged**
