### PR TITLE
Add instructions for running sourceclear and sonarqube locally.

### PR DESCRIPTION
**Pull request by pshapiro4broad**
Someone (@fboulnois ?) asked about running source clear and sonarqube in a local build environment, so I added instructions on running these tools to our README.

Another way to get this information would be to look at our GitHub workflow that runs these tasks, and the terraform deployment we use to copy vault secrets into GitHub secrets.

### CODE REVIEW

**Review by fboulnois — APPROVED** [review]
thank you!

**Comment by fboulnois** [comment]
> Someone (@fboulnois ?) asked about running source clear and sonarqube in a local build environment, so I added instructions on running these tools to our README.
> 
> Another way to get this information would be to look at our GitHub workflow that runs these tasks, and the terraform deployment we use to copy vault secrets into GitHub secrets.

Should we associate a ticket to this?

**Comment by pshapiro4broad** [comment]
> Should we associate a ticket to this?

I don't mind doing it but am not sure updating the README requires a JIRA process. Do we have set of guidelines on what changes require a JIRA to track?

**Review by s-rubenstein — APPROVED** [review]
LGTM

**Pull request merged**
