### PR TITLE
DT-723: Increase number of retries for Integration tests

### PR DESCRIPTION
**Pull request by snf2ye**
https://broadworkbench.atlassian.net/browse/DT-723

### CODE REVIEW

**Review by rushtong — APPROVED** [review]
👍🏽

**Comment by snf2ye** [comment]
I didn't see any retries in the PR run, but we can keep an eye on this for the nightly run.

**Review by rjohanek — APPROVED** [review]
I'm totally down to try this, but do I remember part of the conversation around catalog test failure being that its failing in setup or tear down so this may not help?

**Comment by snf2ye** [comment]
> catalog test failure being that its failing in setup or tear down so this may not help?
Ah, you're totally right - that rings a bell for me. And last night's failure was indeed in the setup.
I'll pause on this change.

**Comment by snf2ye** [comment]
I'm going to move forward with this change since it should not make things worse. But, I will open another ticket to look into the setup flakiness.

**Review by pshapiro4broad — COMMENTED** [review]
I missed this PR, but the default for `maxRetries` is `3`, so an equivalent fix for this issue would be remove `maxRetries` from all configurations.

https://github.com/DataBiosphere/terra-test-runner/blob/main/src/main/java/bio/terra/testrunner/runner/config/TestConfiguration.java#L32

**Pull request merged**
